image: node:13

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries
before_script:
  - cd application/client
  - npm install
  - cd ../server
  - npm install
  - cd ..

# Run JEST test

run_tests:
  stage: test
  script:
    - cd client
    - npm test
    - cd ../server
    - npm test
  artifacts:
    paths:
      - application/server/coverage
      - application/client/coverage

# Publish coverage report on gitlab-pages
pages:
  stage: deploy
  dependencies:
    - run_tests
  script:
    - cd ..
    - mkdir .public
    - cp -r client/coverage/* .public

    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
