image: node:8

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries
before_script:



# Run JEST test
run_tests:
  stage: test
  script:
    #- cd application/server && npm install && npm test
    - cd application/server && npm start
    - cd ..
    - cd application/client && npm install && npm test
  artifacts:
    paths:
      #- application/server/coverage
      - application/client/coverage

# Publish coverage report on gitlab-pages
pages:
  stage: deploy
  dependencies:
    - run_tests
  script:
    - cd ..
    - mkdir .public
    - cp -r client/coverage/* .public

    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
